import type{AIProvider}from"@lifegraph/ai";import type{RetrievalCandidate}from"@lifegraph/retrieval";import{z}from"zod";
export const queryTypeSchema=z.enum(["FACT_LOOKUP","PERSON_LOOKUP","TEMPORAL_RECALL","RELATIONSHIP_LOOKUP","PROJECT_LOOKUP","COMPARISON","SUMMARY","OPEN_ENDED_REFLECTION","FOLLOW_UP"]);
export const queryClassificationSchema=z.object({queryType:queryTypeSchema,entities:z.array(z.string().trim().min(1).max(200)).max(20),topics:z.array(z.string().trim().min(1).max(200)).max(20),temporal:z.object({from:z.string().nullable(),to:z.string().nullable(),mostRecent:z.boolean()}).nullable(),needsClarification:z.boolean(),clarificationQuestion:z.string().trim().min(1).max(500).nullable()});
export const personalAnswerSchema=z.object({answer:z.string().trim().min(1).max(10000).nullable(),confidence:z.enum(["HIGH","MEDIUM","LOW"]),sources:z.array(z.object({objectId:z.uuid(),revisionId:z.uuid(),title:z.string().max(300),excerpt:z.string().trim().min(1).max(500),observedAt:z.string().nullable()})).max(20),unresolvedEntities:z.array(z.string().max(200)).max(20),limitations:z.array(z.string().max(500)).max(20)});
export type QueryClassification=z.infer<typeof queryClassificationSchema>;export type PersonalAnswer=z.infer<typeof personalAnswerSchema>;
export async function classifyQuestion(provider:AIProvider,question:string){return queryClassificationSchema.parse(await provider.generateStructured({schema:queryClassificationSchema,promptVersion:"ask-classifier-v1",system:"Classify a private Personal Graph question. Return JSON only. Never answer it. Set needsClarification when the question itself is underspecified.",input:JSON.stringify({question,requiredShape:{queryType:"one allowed enum",entities:[],topics:[],temporal:null,needsClarification:false,clarificationQuestion:null}})}));}
export type EvidenceCandidate=RetrievalCandidate&{title:string;observedAt:string|null};
export function abstain(reason:string,unresolvedEntities:string[]=[]):PersonalAnswer{return{answer:null,confidence:"LOW",sources:[],unresolvedEntities,limitations:[reason]};}
export function validateAnswerEvidence(raw:unknown,evidence:EvidenceCandidate[]):PersonalAnswer{const answer=personalAnswerSchema.parse(raw);if(answer.confidence==="LOW"||answer.answer===null){if(answer.answer!==null||answer.sources.length)throw new Error("Low-confidence answers must abstain without sources");return answer;}if(!answer.sources.length)throw new Error("Supported answers require sources");const allowed=new Map(evidence.map(item=>[`${item.objectId}:${item.revisionId}`,item]));for(const source of answer.sources){const candidate=allowed.get(`${source.objectId}:${source.revisionId}`);if(!candidate)throw new Error("Answer cited evidence outside the retrieval set");if(!candidate.content.includes(source.excerpt))throw new Error("Citation excerpt is not present in retrieved evidence");source.title=candidate.title;source.observedAt=candidate.observedAt;}return answer;}
export async function answerFromEvidence(provider:AIProvider,question:string,classification:QueryClassification,evidence:EvidenceCandidate[]){if(!evidence.length)return abstain("I could not find enough permitted evidence to answer safely.");const raw=await provider.generateStructured({schema:personalAnswerSchema,promptVersion:"ask-answer-v1",system:"Answer only from the supplied Personal Graph evidence. Return JSON only. Every factual statement must be supported by sources. Copy citation excerpts exactly. If evidence is insufficient or contradictory, return answer null and confidence LOW.",input:JSON.stringify({question,classification,evidence:evidence.map(item=>({objectId:item.objectId,revisionId:item.revisionId,title:item.title,observedAt:item.observedAt,content:item.content})),requiredShape:{answer:"string or null",confidence:"HIGH, MEDIUM, or LOW",sources:[{objectId:"uuid",revisionId:"uuid",title:"server replaces",excerpt:"exact substring",observedAt:null}],unresolvedEntities:[],limitations:[]}})});return validateAnswerEvidence(raw,evidence);}
