import { aiPatchProposalSchema, generateValidatedStructured, validateInlineSelectionPatch } from "@lifegraph/ai";
import { snapshotBlocks } from "@lifegraph/domain";
import { z } from "zod";
import { AIOperationValidationError, RevisionConflictError } from "@lifegraph/db";
import type { NextRequest } from "next/server";
import { apiData, handleApiError, parseJson, requestId, requireApiContext } from "@/lib/api";
import { getAIProvider } from "@/lib/ai";
import { getAIOperationRepository, getObjectRepository } from "@/lib/db";

const inputSchema=z.object({objectId:z.uuid(),baseRevisionId:z.uuid(),blockId:z.uuid(),selectedText:z.string().min(1).max(20_000),instruction:z.string().trim().min(1).max(2_000)});
export async function POST(request:NextRequest){const id=requestId(request);try{const ctx=await requireApiContext(request);if(ctx instanceof Response)return ctx;const input=await parseJson(request,inputSchema);const current=await getObjectRepository().get(ctx.actor.id,input.objectId);if(current.currentRevision.id!==input.baseRevisionId)throw new RevisionConflictError();const snapshot=current.currentRevision.snapshot;const block=snapshotBlocks(snapshot).find(item=>item.id===input.blockId);if(!block||!block.text.includes(input.selectedText))throw new AIOperationValidationError("Selection is not present in the current block");const operationId=crypto.randomUUID();const provider=getAIProvider();const system="You propose one safe JSON patch for a LifeGraph object. Return JSON only, matching the supplied schema. Preserve every field except /body. In the identified block, replace only the selected substring according to the instruction. Return the complete next body as operation.after; operation.before must equal the complete supplied body. Never invent evidence.";const proposal=await generateValidatedStructured(provider,{schema:aiPatchProposalSchema,system,promptVersion:"inline-edit-v1",input:JSON.stringify({requiredIdentity:{operationId,target:{objectId:input.objectId,baseRevisionId:input.baseRevisionId}},instruction:input.instruction,blockId:input.blockId,selectedText:input.selectedText,currentBody:snapshot.body,requiredShape:{summary:"short description",operations:[{op:"replace",path:"/body",before:snapshot.body,after:"complete updated body"}],evidence:[],warnings:[],confidence:"0..1"}})});try{validateInlineSelectionPatch(snapshot,proposal,input.blockId,input.selectedText);}catch(error){throw new AIOperationValidationError(error instanceof Error?error.message:"Invalid inline edit");}const operation=await getAIOperationRepository().createPending(ctx.actor.id,{operationType:"INLINE_PATCH",instruction:input.instruction,targetObjectId:input.objectId,targetRevisionId:input.baseRevisionId,permittedContextIds:[input.objectId],retrievedContextManifest:{requestedScopes:["TARGET_OBJECT"],retrieved:[{objectId:input.objectId,revisionId:input.baseRevisionId,reason:"Inline edit target",permission:"EDIT"}]},provider:provider.name,model:provider.model,promptVersion:"inline-edit-v1",structuredOutput:proposal});return apiData(operation,ctx.requestId,201);}catch(error){return handleApiError(error,id);}}
